const API='/api';
export async function api<T>(path:string, options?:RequestInit):Promise<T>{const r=await fetch(API+path,{headers:{'Content-Type':'application/json',...(options?.headers||{})},...options});if(!r.ok)throw new Error((await r.text())||`Request failed (${r.status})`);return r.json();}
export type Bullet={id:number;text:string;tags?:string[];supporting_facts?:string[];is_locked?:boolean;is_preferred?:boolean};
export type ApiItem={id:number;type:string;title:string;organization?:string;location?:string;start_date?:string;end_date?:string;summary?:string;bullets?:Bullet[]};
export type ApiApplication={id:number;company:string;position:string;job_description:string;job_url?:string;notes?:string;status:string;base_resume_id:number;created_at:string;updated_at?:string};
export type Analysis={id:number;application_id:number;requirements:string[];keywords:string[];technologies:string[];responsibilities:string[];preferred_qualifications:string[]};
export type BaseResume={id:number;name:string;template_id?:string;section_order?:string[];layout_settings?:Record<string,unknown>};
export type Revision={id:number;application_id:number;revision_number:number;status:string;artifact_path?:string;pdf_path?:string;tex_path?:string;page_count?:number;created_at:string};
export type Comparison={well_represented:string[];weakly_represented:string[];library_only:string[];unsupported:string[]};
export type Confirmation={id:number;requirement:string;status:string;context?:string};
export type Proposal={id:number;status:string;payload:any;created_at:string};
export const methods={items:()=>api<ApiItem[]>('/content-items'),item:(id:number)=>api<ApiItem>(`/content-items/${id}`),createItem:(body:Partial<ApiItem>)=>api<ApiItem>('/content-items',{method:'POST',body:JSON.stringify(body)}),editItem:(id:number,body:Partial<ApiItem>)=>api<ApiItem>(`/content-items/${id}`,{method:'PATCH',body:JSON.stringify(body)}),addBullet:(id:number,text:string)=>api<Bullet>(`/content-items/${id}/bullets`,{method:'POST',body:JSON.stringify({text})}),bases:()=>api<BaseResume[]>('/base-resumes'),base:(id:number)=>api<BaseResume>(`/base-resumes/${id}`),apps:()=>api<ApiApplication[]>('/applications'),app:(id:number)=>api<ApiApplication>(`/applications/${id}`),createApp:(body:Partial<ApiApplication>)=>api<ApiApplication>('/applications',{method:'POST',body:JSON.stringify(body)}),analyze:(id:number)=>api<Analysis>(`/applications/${id}/analyze`,{method:'POST'}),comparison:(id:number)=>api<Comparison>(`/applications/${id}/comparison`),confirmations:(id:number)=>api<Confirmation[]>(`/applications/${id}/missing-confirmations`),createConfirmations:(id:number)=>api<Confirmation[]>(`/applications/${id}/missing-confirmations`,{method:'POST'}),updateConfirmation:(id:number,status:string)=>api<Confirmation>(`/missing-confirmations/${id}`,{method:'PATCH',body:JSON.stringify({status})}),proposals:(id:number)=>api<Proposal[]>(`/applications/${id}/proposals`),decision:(id:number,status:string,decisions:Record<string,string>)=>api<Proposal>(`/proposals/${id}/decision`,{method:'POST',body:JSON.stringify({status,decisions})}),generate:(id:number)=>api<Revision>(`/applications/${id}/generate`,{method:'POST'}),revisions:(id:number)=>api<Revision[]>(`/applications/${id}/revisions`)};
